version: "3.8"

services:
  app:
    container_name: biblio_app
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - 8080:80
    networks: 
      - laranet
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: biblio_db
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks: 
      - laranet

  frontend:
    container_name: biblio_frontend
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks: 
      - laranet
    depends_on:
      - app

networks: 
  laranet:
    driver: bridge